### ISSUE TITLE
package Manager support?

### ISSUE THREAD

**Issue by carlos-chaguendo** [pinterest/PINRemoteImage#527]
### Hi,

They could review the possibility of adding Package.swift manifest to support Swift Package Manager

```
// swift-tools-version:5.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "PINRemoteImage",
    products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .library(
            name: "PINRemoteImager",
            targets: ["PINRemoteImage"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "PINRemoteImage",
            dependencies: [],
            path: "Source"),
    ]
)
```

### it's likely they'll have to wrap some of their code in

#if canImport(UIKit)
    import UIKit

    extension UIImage {
    }
#endif

**Comment by xezero** [comment]
Any updates on this?

**Comment by 3a4oT** [comment]
#571

**Comment by Kaspik** [comment]
Current master is still broken (probably due to https://github.com/pinterest/PINRemoteImage/pull/574):

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PINWebPAnimatedImage", referenced from:
      objc-class-ref in PINRemoteImage.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by 3a4oT** [comment]
Yeah, #574 should do the trick

**Comment by garrettmoon** [comment]
Just merged, please let me know if it's working for y'all and I'll put out a new release.

**Comment by Kaspik** [comment]
Current master works for us @garrettmoon ! Seems like PINRemoteImage can go out as 3.0.2 the same as PINCache went yesterday. :)

**Comment by 3a4oT** [comment]
It works for me as well, thanks!

**Comment by yo1995** [comment]
> hello guys, I am trying to use PINRemoteImage on an internal package, but I am running into this error. Any ideas? ![Screenshot 2021-10-29 at 12 16 42](https://user-images.githubusercontent.com/6941489/139425768-ce5b449f-a4eb-4f8f-982a-731f31fb60b1.png) r

I'm also seeing this issue with Xcode 13.1 and Big Sur 11.6.1, on an Intel machine. Have no idea how to solve it except going back to pods 😞 . Since this is 1 of the only few issues we have for using SPM, it may be worth removing the dependency on `PINRemoteImage`.

**Comment by sagesse-cn** [comment]
@yo1995 I just tested SPM with 3.0.0 PINRemoteImage and it works, maybe you should provide a demo project to reproduce the problem.

**Comment by yo1995** [comment]
> @yo1995 I just tested SPM with 3.0.0 PINRemoteImage and it works, maybe you should provide a demo project to reproduce the problem.

Thanks. Tested on a newly created project and it does work, despite the warnings from the cache module. Will need some time to poke around and see why it came up.

**Comment by james-pellow** [comment]
I just created an absolutely fresh project with Xcode 15.0 and added the PINRemoteImage SPM package to the project.  I created an empty swift file with `import PIMRemoteImage` and I get this error with PINRemoteImage 3.0.3.  It looks like this is still an issue, and I don't see any resolution suggestions here.  What are people doing with this?
